version: '3.7'

services:
  api:
    container_name: 'chat-real-time-api'
    build:
      context: ./api/.
      target: development
    volumes:
      - ./api/.:/usr/src/app
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - chat-real-time

  mysql:
    image: mysql:8.3
    container_name: chat-real-time-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - mysql_data_container:/var/lib/mysql
    networks:
      - chat-real-time

networks:
  chat-real-time:

volumes:
  mysql_data_container: